version: '3.9'
services:
  db:
    build: ./
    container_name: ${PRJ_NAME}db
    environment:
      MYSQL_ROOT_PASSWORD: xpto
      MYSQL_DATABASE: xpto
      MYSQL_USER: xpto
      MYSQL_PASSWORD: xpto
    volumes:
      - ./dados:/dados
    ports:
      - 3306:3306

    networks:
      - db

  docker:
    build: ./docker/.
    container_name: ${PRJ_NAME}docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true 
    
networks:
  db: